version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./server/docker/Dockerfile
    command: /bin/bash -c "while sleep 1000; do :; done"
    working_dir: /home/api
    networks:
      - api-network
    ports:
      - "3008:3008"
    volumes:
      - ./server/:/home/api:cached
      - ./server/dbms/ddl/:/home/dbms/ddl:cached

  app:
    build:
      context: .
      dockerfile: ./client/docker/Dockerfile
    command: /bin/bash -c "while sleep 1000; do :; done"
    working_dir: /home/app
    networks:
      - api-network
    ports:
      - "3000:3000"
    volumes:
      - ./client:/home/app:cached

  dbms:
    image: mariadb:10
    restart: always
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_ROOT_PASSWORD=rootpassword
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
    ]
    volumes:
      - ./server/dbms/mariadb.cnf:/etc/mysql/mariadb.cnf
      - ./server/dbms/dbms-data:/var/lib/mysql
    networks:
      - api-network

  proxy:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/api-dev.nginx.conf:/etc/nginx/conf.d/api.nginx.conf
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
    name: api-network
