### CREATE POST
POST localhost:4000/posts
Accept: application/json
Content-Type: application/json

{
    "title": "Title 1"
}


### POST /posts
POST localhost:4001/posts/e15a4c94/comments
Accept: application/json
Content-Type: application/json

{
    "content": "Mugiwara no Luffy"
}

### GET /posts
GET localhost:4002/posts
Accept: application/json
